alter table xtf_geopoint add column updated_at datetime NOT NULL;
update xtf_geopoint set updated_at=now();
alter table xtf_dublincoreterm add column updated_at datetime NOT NULL;
update xtf_dublincoreterm set updated_at =now();
alter table xtf_arkobject add column updated_at datetime NOT NULL;
update xtf_arkobject set updated_at =now();
alter table xtf_arkset add column updated_at datetime NOT NULL;
update xtf_arkset set updated_at =now();
alter table xtf_arksetmember add column updated_at datetime NOT NULL;
update xtf_arksetmember set updated_at =now();
alter table themed_collection_themedcollection add column updated_at datetime NOT NULL;
update themed_collection_themedcollection set updated_at =now();
alter table themed_collection_themedcollectionsidebar add column updated_at datetime NOT NULL;
update themed_collection_themedcollectionsidebar set updated_at =now();
alter table xtf_geopoint add column created_at datetime NOT NULL;
update xtf_geopoint set created_at =now();
alter table xtf_dublincoreterm add column created_at datetime NOT NULL;
update xtf_dublincoreterm set created_at =now();
alter table xtf_arkobject add column created_at datetime NOT NULL;
update xtf_arkobject set created_at =now();
alter table xtf_arkset add column created_at datetime NOT NULL;
update xtf_arkset set created_at =now();
alter table xtf_arksetmember add column created_at datetime NOT NULL;
update xtf_arksetmember set created_at =now();
alter table themed_collection_themedcollection add column created_at datetime NOT NULL;
update themed_collection_themedcollection set created_at =now();
alter table themed_collection_themedcollectionsidebar add column created_at datetime NOT NULL;
update themed_collection_themedcollectionsidebar set created_at =now();
